<?php
/**
 * Magmodules.eu - http://www.magmodules.eu
 *
 * NOTICE OF LICENSE
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magmodules.eu so we can send you a copy immediately.
 *
 * @category      Magmodules
 * @package       Magmodules_Kiyoh
 * @author        Magmodules <info@magmodules.eu)
 * @copyright     Copyright (c) 2017 (http://www.magmodules.eu)
 * @license       http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$sidebarreviews = $this->getSidebarCollection('left');
$total = $this->getTotalScore();
?>
<?php if ($sidebarreviews && $total): ?>
    <div class="block kiyoh-sidebar">
        <div class="block-title">
            <strong><span><?php echo $this->__('Kiyoh') ?></span></strong>
        </div>
        <?php if ($total->getPercentage() > 0): ?>
            <?php if ($this->getSnippetsEnabled('left')): ?>
                <div class="block-content" itemscope itemtype="http://schema.org/WebPage">
                    <div class="total-block-stars"><span style="width: <?php echo $total->getPercentage(); ?>%"></span>
                    </div>
                    <div class="total-block-text" itemprop="aggregateRating" itemscope
                         itemtype="http://schema.org/AggregateRating">
                        <p><strong><span itemprop="ratingValue"><?php echo $total->getStarsQty(); ?></span> / <span
                                        itemprop="bestRating">10</span></strong></p>
                        <p class="based-on"><?php echo $this->__('Based on %s reviews', '<span itemprop="ratingCount">' . $total->getVotes() . '</span>'); ?></p>
                    </div>
                </div>
            <?php else: ?>
                <div class="block-content">
                    <div class="total-block-stars"><span style="width: <?php echo $total->getPercentage(); ?>%"></span>
                    </div>
                    <div class="total-block-text">
                        <p><strong><?php echo $total->getStarsQty(); ?> / 10</strong></p>
                        <p class="based-on"><?php echo $this->__('Based on %s reviews', '<span itemprop="ratingCount">' . $total->getVotes() . '</span>'); ?></p>
                    </div>
                </div>
            <?php endif; ?>
        <?php endif; ?>
        <?php $i = 0;
        foreach ($sidebarreviews as $sidebarreview): ?>
            <?php $content = $this->formatContent($sidebarreview, 'left'); ?>
            <div class="block-content">
                <div class="kiyoh-sidebar-block">
                    <p><u><?php echo $sidebarreview->getCustomerName(); ?></u> <?php echo $content; ?></p>
                    <span class="rating-name"><?php echo Mage::helper('core')->formatDate($sidebarreview->getDateCreated(), 'medium', false); ?></span>
                    <?php if ($sidebarreview->getScore()): ?>
                        <span class="rating-empty"><span
                                    class="rating-star-<?php echo $sidebarreview->getScore(); ?>"></span></span>
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>
        <?php if ($reviewurl = $this->getReviewsUrl('left')): ?>
            <div class="block-content">
                <img src="<?php echo $this->getSkinUrl('magmodules/kiyoh/images/logo.png'); ?>" class="kiyoh-logo">
                <div class="actions">
                    <?php echo $reviewurl; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>